//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiddenWallet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiddenWallet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced.
        /// </summary>
        internal static string FormMain_backgroundWorkerSyncWallet_RunWorkerCompleted_Wallet_is_synced {
            get {
                return ResourceManager.GetString("FormMain_backgroundWorkerSyncWallet_RunWorkerCompleted_Wallet_is_synced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing....
        /// </summary>
        internal static string FormMain_SetProgressBar_Syncing_wallet___ {
            get {
                return ResourceManager.GetString("FormMain_SetProgressBar_Syncing_wallet___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        internal static string Incorrect_password {
            get {
                return ResourceManager.GetString("Incorrect_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string InputDialog_Show__Ok {
            get {
                return ResourceManager.GetString("InputDialog_Show__Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string InputDialog_Show_Password {
            get {
                return ResourceManager.GetString("InputDialog_Show_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please backup your wallet file.
        /// </summary>
        internal static string Please_backup_your_wallet_file {
            get {
                return ResourceManager.GetString("Please_backup_your_wallet_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet created.
        /// </summary>
        internal static string Wallet_created {
            get {
                return ResourceManager.GetString("Wallet_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet file not found.
        /// </summary>
        internal static string Wallet_file_not_found {
            get {
                return ResourceManager.GetString("Wallet_file_not_found", resourceCulture);
            }
        }
    }
}
