trigger:
- master

strategy:
  matrix:
    linux:
      runtime: 'linux-x64'
    mac:
      runtime: 'osx-x64'
    windows:
      runtime: 'win7-x64'

pool:
  vmImage: ubuntu-16.04

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 3'
  inputs:
    version: 3.1.x

- task: Bash@3
  displayName: 'Build and compare'
  inputs:
    targetType: 'inline'
    script: |
      cd WalletWasabi.Gui;
      for i in `seq 2`; 
      do 
      dotnet clean --configuration Release && dotnet publish --configuration Release --force --output "./dist${i}" --self-contained true --runtime "$(runtime)" /p:VersionPrefix=1.1.20 --disable-parallel --no-cache /p:DebugType=none /p:DebugSymbols=false /p:ErrorReport=none /p:DocumentationFile=\"\" /p:Deterministic=true; 
      done;
      diff <(find ./dist1/ -type f -exec md5sum {} + | cut -f1 -d' ' | sort) <(find ./dist2/ -type f -exec md5sum {} + | cut -f1 -d' '| sort);

