trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 3'
  inputs:
    version: 3.1.x

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      dotnet run -p .\WalletWasabi.Packager\ --onlybinaries
      Remove-Item -Recurse -ErrorAction SilentlyContinue .\WalletWasabi.Gui\bin\dist1
      Rename-Item -Path .\WalletWasabi.Gui\bin\dist -NewName dist1
      dotnet run -p .\WalletWasabi.Packager\ --onlybinaries
      git diff --no-index .\WalletWasabi.Gui\bin\dist .\WalletWasabi.Gui\bin\dist1
      exit $LASTEXITCODE
    failOnStderr: false