trigger:
- master

pool:
  vmImage: windows-latest

steps:
- checkout: self
  path: WalletWasabi

- task: UseDotNet@2
  displayName: 'Install .NET Core 3'
  inputs:
    version: 3.1.x

- task: PowerShell@2
  displayName: 'Build and compare'
  inputs:
    targetType: 'inline'
    script: |
      # Change git output from stderr to stdout https://github.com/dahlbyk/posh-git/issues/109.
      $env:GIT_REDIRECT_STDERR = '2>&1'
      Remove-Item -Recurse -ErrorAction SilentlyContinue -Force .\WalletWasabi.Gui\bin
      Remove-Item -Recurse -ErrorAction SilentlyContinue -Force ..\WalletWasabiClone
      robocopy ..\WalletWasabi ..\WalletWasabiClone /COPYALL /S /XD ".git"
      dotnet run -p .\WalletWasabi.Packager --onlybinaries
      dotnet run -p ..\WalletWasabiClone\WalletWasabi.Packager --onlybinaries
      git diff --no-index ..\WalletWasabiClone\WalletWasabi.Gui\bin\dist .\WalletWasabi.Gui\bin\dist
      if (0 -eq $LASTEXITCODE)
      {
          Write-Output "Deterministic build succeed"
      }
      else
      {
          Write-Output "Deterministic build failed"
      }
      exit $LASTEXITCODE