namespace WalletWasabi.WabiSabi.Crypto.CredentialRequesting;

public record RealCredentialsRequestData(RealCredentialsRequest CredentialsRequest, CredentialsResponseValidation CredentialsResponseValidation);
