using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using WalletWasabi.Fluent.Generators.Analyzers;

namespace WalletWasabi.Fluent.Generators.Generators;

[Generator(LanguageNames.CSharp)]
internal class UiContextConstructorGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var classDeclarationsProvider = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) =>
					node is ClassDeclarationSyntax classDeclaration
					&& classDeclaration.Identifier.Text != "RoutableViewModel"
					&& classDeclaration.Identifier.Text.EndsWith("ViewModel", StringComparison.Ordinal),
				transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
			.Where(static m => m is not null)
			.Collect();

		var compilationAndClasses = context.CompilationProvider.Combine(classDeclarationsProvider);

		context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
		{
			var (compilation, classDeclarations) = source;

			var toGenerate =
				from cls in classDeclarations
				where !cls.IsSourceGenerated() // assuming you have this extension still
				group cls by cls.Identifier.ValueText into g
				select g.First();

			foreach (var classDeclaration in toGenerate)
			{
				var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);

				if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
				{
					continue;
				}

				var sourceCodeFiles = GenerateConstructors(classDeclaration, model, classSymbol);

				foreach (var sourceCode in sourceCodeFiles)
				{
					var fileName = classDeclaration.Identifier.ValueText + UiContextAnalyzer.UiContextFileSuffix;
					spc.AddSource(fileName, sourceCode);
				}
			}
		});
	}

	private static IEnumerable<string> GenerateConstructors(
		ClassDeclarationSyntax classDeclaration,
		SemanticModel semanticModel,
		INamedTypeSymbol classSymbol)
	{
		var className = classSymbol.Name;
		var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();

		var constructors = classDeclaration
			.ChildNodes()
			.OfType<ConstructorDeclarationSyntax>()
			.ToArray();

		foreach (var constructor in constructors)
		{
			if (classDeclaration.GetUiContextReferences(semanticModel).Count == 0)
			{
				if (!classDeclaration.IsAbstractClass(semanticModel) && constructor.IsPublic())
				{
					continue;
				}
			}
			// if constructor already has a UIContext parameter, leave it be. Don't generate a new constructor and use the current one for FluentNavigation.
			else if (constructor.ParameterList.Parameters.Any(p => p.Type.IsUiContextType(semanticModel)))
			{
				// it must be public though
				if (constructor.IsPublic())
				{
					continue;
				}
			}
			else
			{
				var constructorArgs = constructor.ParameterList.Parameters
					.Select(x => x.Identifier.ValueText)
					.ToArray();

				var hasConstructorArgs = constructorArgs.Length != 0;
				var constructorArgsString = string.Join(",", constructorArgs);
				var constructorString = hasConstructorArgs
					? $": this({constructorArgsString})"
					: $": this()";

				var parameterUsings = constructor.ParameterList.Parameters
					.Where(p => p.Type is not null)
					.Select(p => semanticModel.GetTypeInfo(p.Type!))
					.Where(t => t.Type is not null)
					.Select(t => $"using {t.Type!.ContainingNamespace.ToDisplayString()};")
					.ToArray();

				var uiContextParameter = SyntaxFactory
					.Parameter(SyntaxFactory.Identifier("uiContext").WithLeadingTrivia(SyntaxFactory.Space))
					.WithType(SyntaxFactory.ParseTypeName("UiContext"));

				var parametersString = constructor.ParameterList.Parameters.Insert(0, uiContextParameter).ToFullString();

				var usings = string.Join("\n", parameterUsings.Distinct().OrderBy(x => x));

				var code =
					$$"""
					// <auto-generated />
					
					#nullable enable
					{{usings}}
					using WalletWasabi.Fluent.Models.UI;

					namespace {{namespaceName}};

					partial class {{className}}
					{
						public {{className}}({{parametersString}}){{constructorString}}
						{
							UiContext = uiContext;
						}
					}
					""";

				yield return code;
			}
		}
	}
}
