//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletWasabi.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WalletWasabi.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Utils_Plural {
            get {
                return ResourceManager.GetString("Utils_Plural", resourceCulture);
            }
        }
        
        public static string Words_About {
            get {
                return ResourceManager.GetString("Words_About", resourceCulture);
            }
        }
        
        public static string Words_Action {
            get {
                return ResourceManager.GetString("Words_Action", resourceCulture);
            }
        }
        
        public static string Words_Add {
            get {
                return ResourceManager.GetString("Words_Add", resourceCulture);
            }
        }
        
        public static string Words_Address {
            get {
                return ResourceManager.GetString("Words_Address", resourceCulture);
            }
        }
        
        public static string Words_Addresses {
            get {
                return ResourceManager.GetString("Words_Addresses", resourceCulture);
            }
        }
        
        public static string Words_Advanced {
            get {
                return ResourceManager.GetString("Words_Advanced", resourceCulture);
            }
        }
        
        public static string Words_Amount {
            get {
                return ResourceManager.GetString("Words_Amount", resourceCulture);
            }
        }
        
        public static string Words_Auto {
            get {
                return ResourceManager.GetString("Words_Auto", resourceCulture);
            }
        }
        
        public static string Words_and {
            get {
                return ResourceManager.GetString("Words_and", resourceCulture);
            }
        }
        
        public static string Words_Backend {
            get {
                return ResourceManager.GetString("Words_Backend", resourceCulture);
            }
        }
        
        public static string Words_Background {
            get {
                return ResourceManager.GetString("Words_Background", resourceCulture);
            }
        }
        
        public static string Words_Bitcoin {
            get {
                return ResourceManager.GetString("Words_Bitcoin", resourceCulture);
            }
        }
        
        public static string Words_Broadcast {
            get {
                return ResourceManager.GetString("Words_Broadcast", resourceCulture);
            }
        }
        
        public static string Words_Browse {
            get {
                return ResourceManager.GetString("Words_Browse", resourceCulture);
            }
        }
        
        public static string Words_BTC {
            get {
                return ResourceManager.GetString("Words_BTC", resourceCulture);
            }
        }
        
        public static string Words_Bug {
            get {
                return ResourceManager.GetString("Words_Bug", resourceCulture);
            }
        }
        
        public static string Words_Cancel {
            get {
                return ResourceManager.GetString("Words_Cancel", resourceCulture);
            }
        }
        
        public static string Words_Change {
            get {
                return ResourceManager.GetString("Words_Change", resourceCulture);
            }
        }
        
        public static string Words_Clearnet {
            get {
                return ResourceManager.GetString("Words_Clearnet", resourceCulture);
            }
        }
        
        public static string Words_Close {
            get {
                return ResourceManager.GetString("Words_Close", resourceCulture);
            }
        }
        
        public static string Words_Code {
            get {
                return ResourceManager.GetString("Words_Code", resourceCulture);
            }
        }
        
        public static string Words_Coins {
            get {
                return ResourceManager.GetString("Words_Coins", resourceCulture);
            }
        }
        
        public static string Words_ColdCard {
            get {
                return ResourceManager.GetString("Words_ColdCard", resourceCulture);
            }
        }
        
        public static string Words_Computer {
            get {
                return ResourceManager.GetString("Words_Computer", resourceCulture);
            }
        }
        
        public static string Words_Config {
            get {
                return ResourceManager.GetString("Words_Config", resourceCulture);
            }
        }
        
        public static string Words_confirmation {
            get {
                return ResourceManager.GetString("Words_confirmation", resourceCulture);
            }
        }
        
        public static string Words_Confirmed {
            get {
                return ResourceManager.GetString("Words_Confirmed", resourceCulture);
            }
        }
        
        public static string Words_Connect {
            get {
                return ResourceManager.GetString("Words_Connect", resourceCulture);
            }
        }
        
        public static string Words_Continue {
            get {
                return ResourceManager.GetString("Words_Continue", resourceCulture);
            }
        }
        
        public static string Words_Coordinator {
            get {
                return ResourceManager.GetString("Words_Coordinator", resourceCulture);
            }
        }
        
        public static string Words_Coordination {
            get {
                return ResourceManager.GetString("Words_Coordination", resourceCulture);
            }
        }
        
        public static string Words_Copy {
            get {
                return ResourceManager.GetString("Words_Copy", resourceCulture);
            }
        }
        
        public static string Words_Core {
            get {
                return ResourceManager.GetString("Words_Core", resourceCulture);
            }
        }
        
        public static string Words_Count {
            get {
                return ResourceManager.GetString("Words_Count", resourceCulture);
            }
        }
        
        public static string Words_Create {
            get {
                return ResourceManager.GetString("Words_Create", resourceCulture);
            }
        }
        
        public static string Words_Custom {
            get {
                return ResourceManager.GetString("Words_Custom", resourceCulture);
            }
        }
        
        public static string Words_Dark {
            get {
                return ResourceManager.GetString("Words_Dark", resourceCulture);
            }
        }
        
        public static string Words_Data {
            get {
                return ResourceManager.GetString("Words_Data", resourceCulture);
            }
        }
        
        public static string Words_day {
            get {
                return ResourceManager.GetString("Words_day", resourceCulture);
            }
        }
        
        public static string Words_Days {
            get {
                return ResourceManager.GetString("Words_Days", resourceCulture);
            }
        }
        
        public static string Words_Display {
            get {
                return ResourceManager.GetString("Words_Display", resourceCulture);
            }
        }
        
        public static string Words_Docs {
            get {
                return ResourceManager.GetString("Words_Docs", resourceCulture);
            }
        }
        
        public static string Words_Documentation {
            get {
                return ResourceManager.GetString("Words_Documentation", resourceCulture);
            }
        }
        
        public static string Words_Dust {
            get {
                return ResourceManager.GetString("Words_Dust", resourceCulture);
            }
        }
        
        public static string Words_Enable {
            get {
                return ResourceManager.GetString("Words_Enable", resourceCulture);
            }
        }
        
        public static string Words_Endpoint {
            get {
                return ResourceManager.GetString("Words_Endpoint", resourceCulture);
            }
        }
        
        public static string Words_Exclude {
            get {
                return ResourceManager.GetString("Words_Exclude", resourceCulture);
            }
        }
        
        public static string Words_FAQ {
            get {
                return ResourceManager.GetString("Words_FAQ", resourceCulture);
            }
        }
        
        public static string Words_Fee {
            get {
                return ResourceManager.GetString("Words_Fee", resourceCulture);
            }
        }
        
        public static string Words_File {
            get {
                return ResourceManager.GetString("Words_File", resourceCulture);
            }
        }
        
        public static string Words_Find {
            get {
                return ResourceManager.GetString("Words_Find", resourceCulture);
            }
        }
        
        public static string Words_Folder {
            get {
                return ResourceManager.GetString("Words_Folder", resourceCulture);
            }
        }
        
        public static string Words_Format {
            get {
                return ResourceManager.GetString("Words_Format", resourceCulture);
            }
        }
        
        public static string Words_Freeze {
            get {
                return ResourceManager.GetString("Words_Freeze", resourceCulture);
            }
        }
        
        public static string Words_General {
            get {
                return ResourceManager.GetString("Words_General", resourceCulture);
            }
        }
        
        public static string Words_GitHub {
            get {
                return ResourceManager.GetString("Words_GitHub", resourceCulture);
            }
        }
        
        public static string Words_GPU {
            get {
                return ResourceManager.GetString("Words_GPU", resourceCulture);
            }
        }
        
        public static string Words_Guide {
            get {
                return ResourceManager.GetString("Words_Guide", resourceCulture);
            }
        }
        
        public static string Words_Hardware {
            get {
                return ResourceManager.GetString("Words_Hardware", resourceCulture);
            }
        }
        
        public static string Words_hour {
            get {
                return ResourceManager.GetString("Words_hour", resourceCulture);
            }
        }
        
        public static string Words_Hours {
            get {
                return ResourceManager.GetString("Words_Hours", resourceCulture);
            }
        }
        
        public static string Words_Id {
            get {
                return ResourceManager.GetString("Words_Id", resourceCulture);
            }
        }
        
        public static string Words_Import {
            get {
                return ResourceManager.GetString("Words_Import", resourceCulture);
            }
        }
        
        public static string Words_Info {
            get {
                return ResourceManager.GetString("Words_Info", resourceCulture);
            }
        }
        
        public static string Words_Information {
            get {
                return ResourceManager.GetString("Words_Information", resourceCulture);
            }
        }
        
        public static string Words_Input {
            get {
                return ResourceManager.GetString("Words_Input", resourceCulture);
            }
        }
        
        public static string Words_Interface {
            get {
                return ResourceManager.GetString("Words_Interface", resourceCulture);
            }
        }
        
        public static string Words_Knots {
            get {
                return ResourceManager.GetString("Words_Knots", resourceCulture);
            }
        }
        
        public static string Words_Label {
            get {
                return ResourceManager.GetString("Words_Label", resourceCulture);
            }
        }
        
        public static string Words_Labels {
            get {
                return ResourceManager.GetString("Words_Labels", resourceCulture);
            }
        }
        
        public static string Words_Ledger {
            get {
                return ResourceManager.GetString("Words_Ledger", resourceCulture);
            }
        }
        
        public static string Words_License {
            get {
                return ResourceManager.GetString("Words_License", resourceCulture);
            }
        }
        
        public static string Words_Logs {
            get {
                return ResourceManager.GetString("Words_Logs", resourceCulture);
            }
        }
        
        public static string Words_Main {
            get {
                return ResourceManager.GetString("Words_Main", resourceCulture);
            }
        }
        
        public static string Words_minute {
            get {
                return ResourceManager.GetString("Words_minute", resourceCulture);
            }
        }
        
        public static string Words_Mining {
            get {
                return ResourceManager.GetString("Words_Mining", resourceCulture);
            }
        }
        
        public static string Words_Mode {
            get {
                return ResourceManager.GetString("Words_Mode", resourceCulture);
            }
        }
        
        public static string Words_Months {
            get {
                return ResourceManager.GetString("Words_Months", resourceCulture);
            }
        }
        
        public static string Words_Network {
            get {
                return ResourceManager.GetString("Words_Network", resourceCulture);
            }
        }
        
        public static string Words_New {
            get {
                return ResourceManager.GetString("Words_New", resourceCulture);
            }
        }
        
        public static string Words_No {
            get {
                return ResourceManager.GetString("Words_No", resourceCulture);
            }
        }
        
        public static string Words_Node {
            get {
                return ResourceManager.GetString("Words_Node", resourceCulture);
            }
        }
        
        public static string Words_Onion {
            get {
                return ResourceManager.GetString("Words_Onion", resourceCulture);
            }
        }
        
        public static string Words_Open {
            get {
                return ResourceManager.GetString("Words_Open", resourceCulture);
            }
        }
        
        public static string Words_Output {
            get {
                return ResourceManager.GetString("Words_Output", resourceCulture);
            }
        }
        
        public static string Words_P2P {
            get {
                return ResourceManager.GetString("Words_P2P", resourceCulture);
            }
        }
        
        public static string Words_Paste {
            get {
                return ResourceManager.GetString("Words_Paste", resourceCulture);
            }
        }
        
        public static string Words_Pending {
            get {
                return ResourceManager.GetString("Words_Pending", resourceCulture);
            }
        }
        
        public static string Words_Questions {
            get {
                return ResourceManager.GetString("Words_Questions", resourceCulture);
            }
        }
        
        public static string Words_Recover {
            get {
                return ResourceManager.GetString("Words_Recover", resourceCulture);
            }
        }
        
        public static string Words_Rate {
            get {
                return ResourceManager.GetString("Words_Rate", resourceCulture);
            }
        }
        
        public static string Words_RegTest {
            get {
                return ResourceManager.GetString("Words_RegTest", resourceCulture);
            }
        }
        
        public static string Words_Report {
            get {
                return ResourceManager.GetString("Words_Report", resourceCulture);
            }
        }
        
        public static string Words_Run {
            get {
                return ResourceManager.GetString("Words_Run", resourceCulture);
            }
        }
        
        public static string Words_sats {
            get {
                return ResourceManager.GetString("Words_sats", resourceCulture);
            }
        }
        
        public static string Words_second {
            get {
                return ResourceManager.GetString("Words_second", resourceCulture);
            }
        }
        
        public static string Words_Settings {
            get {
                return ResourceManager.GetString("Words_Settings", resourceCulture);
            }
        }
        
        public static string Words_Send {
            get {
                return ResourceManager.GetString("Words_Send", resourceCulture);
            }
        }
        
        public static string Words_Signed {
            get {
                return ResourceManager.GetString("Words_Signed", resourceCulture);
            }
        }
        
        public static string Words_Skip {
            get {
                return ResourceManager.GetString("Words_Skip", resourceCulture);
            }
        }
        
        public static string Words_Software {
            get {
                return ResourceManager.GetString("Words_Software", resourceCulture);
            }
        }
        
        public static string Words_Source {
            get {
                return ResourceManager.GetString("Words_Source", resourceCulture);
            }
        }
        
        public static string Words_Start {
            get {
                return ResourceManager.GetString("Words_Start", resourceCulture);
            }
        }
        
        public static string Words_Startup {
            get {
                return ResourceManager.GetString("Words_Startup", resourceCulture);
            }
        }
        
        public static string Words_Stats {
            get {
                return ResourceManager.GetString("Words_Stats", resourceCulture);
            }
        }
        
        public static string Words_Status {
            get {
                return ResourceManager.GetString("Words_Status", resourceCulture);
            }
        }
        
        public static string Words_Success {
            get {
                return ResourceManager.GetString("Words_Success", resourceCulture);
            }
        }
        
        public static string Words_Support {
            get {
                return ResourceManager.GetString("Words_Support", resourceCulture);
            }
        }
        
        public static string Words_System {
            get {
                return ResourceManager.GetString("Words_System", resourceCulture);
            }
        }
        
        public static string Words_TestNet {
            get {
                return ResourceManager.GetString("Words_TestNet", resourceCulture);
            }
        }
        
        public static string Words_Next {
            get {
                return ResourceManager.GetString("Words_Next", resourceCulture);
            }
        }
        
        public static string Words_Threshold {
            get {
                return ResourceManager.GetString("Words_Threshold", resourceCulture);
            }
        }
        
        public static string Words_Tor {
            get {
                return ResourceManager.GetString("Words_Tor", resourceCulture);
            }
        }
        
        public static string Words_Transaction {
            get {
                return ResourceManager.GetString("Words_Transaction", resourceCulture);
            }
        }
        
        public static string Words_Trezor {
            get {
                return ResourceManager.GetString("Words_Trezor", resourceCulture);
            }
        }
        
        public static string Words_Type {
            get {
                return ResourceManager.GetString("Words_Type", resourceCulture);
            }
        }
        
        public static string Words_TXID {
            get {
                return ResourceManager.GetString("Words_TXID", resourceCulture);
            }
        }
        
        public static string Words_URI {
            get {
                return ResourceManager.GetString("Words_URI", resourceCulture);
            }
        }
        
        public static string Words_User {
            get {
                return ResourceManager.GetString("Words_User", resourceCulture);
            }
        }
        
        public static string Words_Version {
            get {
                return ResourceManager.GetString("Words_Version", resourceCulture);
            }
        }
        
        public static string Words_Wallet {
            get {
                return ResourceManager.GetString("Words_Wallet", resourceCulture);
            }
        }
        
        public static string Words_Website {
            get {
                return ResourceManager.GetString("Words_Website", resourceCulture);
            }
        }
        
        public static string Words_Weeks {
            get {
                return ResourceManager.GetString("Words_Weeks", resourceCulture);
            }
        }
        
        public static string Words_Yes {
            get {
                return ResourceManager.GetString("Words_Yes", resourceCulture);
            }
        }
        
        public static string Sentences_Amount_sent {
            get {
                return ResourceManager.GetString("Sentences_Amount_sent", resourceCulture);
            }
        }
        
        public static string Sentences_Amount_received {
            get {
                return ResourceManager.GetString("Sentences_Amount_received", resourceCulture);
            }
        }
        
        public static string Sentences_BackendStatus {
            get {
                return ResourceManager.GetString("Sentences_BackendStatus", resourceCulture);
            }
        }
        
        public static string Sentences_BugReport {
            get {
                return ResourceManager.GetString("Sentences_BugReport", resourceCulture);
            }
        }
        
        public static string Sentences_GetStarted {
            get {
                return ResourceManager.GetString("Sentences_GetStarted", resourceCulture);
            }
        }
        
        public static string Sentences_Hide_sensitive_data {
            get {
                return ResourceManager.GetString("Sentences_Hide_sensitive_data", resourceCulture);
            }
        }
        
        public static string Sentences_InvalidURI {
            get {
                return ResourceManager.GetString("Sentences_InvalidURI", resourceCulture);
            }
        }
        
        public static string Sentences_less_than {
            get {
                return ResourceManager.GetString("Sentences_less_than", resourceCulture);
            }
        }
        
        public static string Sentences_MITLicense {
            get {
                return ResourceManager.GetString("Sentences_MITLicense", resourceCulture);
            }
        }
        
        public static string Sentences_MustBeANumberBetween {
            get {
                return ResourceManager.GetString("Sentences_MustBeANumberBetween", resourceCulture);
            }
        }
        
        public static string Sentences_Show_sensitive_data {
            get {
                return ResourceManager.GetString("Sentences_Show_sensitive_data", resourceCulture);
            }
        }
        
        public static string Sentences_SourceCode {
            get {
                return ResourceManager.GetString("Sentences_SourceCode", resourceCulture);
            }
        }
        
        public static string Sentences_UserSupport {
            get {
                return ResourceManager.GetString("Sentences_UserSupport", resourceCulture);
            }
        }
        
        public static string AboutViewModel_Title {
            get {
                return ResourceManager.GetString("AboutViewModel_Title", resourceCulture);
            }
        }
        
        public static string AboutViewModel_Caption {
            get {
                return ResourceManager.GetString("AboutViewModel_Caption", resourceCulture);
            }
        }
        
        public static string AboutViewModel_Keywords {
            get {
                return ResourceManager.GetString("AboutViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string AddWalletPageViewModel_Title {
            get {
                return ResourceManager.GetString("AddWalletPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string AddWalletPageViewModel_Caption {
            get {
                return ResourceManager.GetString("AddWalletPageViewModel_Caption", resourceCulture);
            }
        }
        
        public static string AddWalletPageViewModel_Keywords {
            get {
                return ResourceManager.GetString("AddWalletPageViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string AddWalletPageViewModel_OpenFiles_Title {
            get {
                return ResourceManager.GetString("AddWalletPageViewModel_OpenFiles_Title", resourceCulture);
            }
        }
        
        public static string AddWalletPageViewModel_Error_UnableImport_Title {
            get {
                return ResourceManager.GetString("AddWalletPageViewModel_Error_UnableImport_Title", resourceCulture);
            }
        }
        
        public static string AddWalletPageViewModel_Error_UnableImport_Caption {
            get {
                return ResourceManager.GetString("AddWalletPageViewModel_Error_UnableImport_Caption", resourceCulture);
            }
        }
        
        public static string AdvancedSettingsTabViewModel_Title {
            get {
                return ResourceManager.GetString("AdvancedSettingsTabViewModel_Title", resourceCulture);
            }
        }
        
        public static string AdvancedSettingsTabViewModel_Caption {
            get {
                return ResourceManager.GetString("AdvancedSettingsTabViewModel_Caption", resourceCulture);
            }
        }
        
        public static string AdvancedSettingsTabViewModel_Keywords {
            get {
                return ResourceManager.GetString("AdvancedSettingsTabViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string BitcoinTabSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("BitcoinTabSettingsViewModel_Title", resourceCulture);
            }
        }
        
        public static string BitcoinTabSettingsViewModel_Caption {
            get {
                return ResourceManager.GetString("BitcoinTabSettingsViewModel_Caption", resourceCulture);
            }
        }
        
        public static string BitcoinTabSettingsViewModel_Keywords {
            get {
                return ResourceManager.GetString("BitcoinTabSettingsViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string BitcoinTabSettingsViewModel_Error_InvalidEndpoint {
            get {
                return ResourceManager.GetString("BitcoinTabSettingsViewModel_Error_InvalidEndpoint", resourceCulture);
            }
        }
        
        public static string BitcoinTabSettingsViewModel_Error_InvalidSeparator {
            get {
                return ResourceManager.GetString("BitcoinTabSettingsViewModel_Error_InvalidSeparator", resourceCulture);
            }
        }
        
        public static string BitcoinTabSettingsViewModel_Error_InvalidDustThreahold {
            get {
                return ResourceManager.GetString("BitcoinTabSettingsViewModel_Error_InvalidDustThreahold", resourceCulture);
            }
        }
        
        public static string BroadcasterViewModel_Title {
            get {
                return ResourceManager.GetString("BroadcasterViewModel_Title", resourceCulture);
            }
        }
        
        public static string BroadcasterViewModel_Caption {
            get {
                return ResourceManager.GetString("BroadcasterViewModel_Caption", resourceCulture);
            }
        }
        
        public static string BroadcasterViewModel_Keywords {
            get {
                return ResourceManager.GetString("BroadcasterViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string BugReportLinkViewModel_Title {
            get {
                return ResourceManager.GetString("BugReportLinkViewModel_Title", resourceCulture);
            }
        }
        
        public static string BugReportLinkViewModel_Caption {
            get {
                return ResourceManager.GetString("BugReportLinkViewModel_Caption", resourceCulture);
            }
        }
        
        public static string BugReportLinkViewModel_Keywords {
            get {
                return ResourceManager.GetString("BugReportLinkViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string BuyViewModel_Title {
            get {
                return ResourceManager.GetString("BuyViewModel_Title", resourceCulture);
            }
        }
        
        public static string BuyViewModel_Caption {
            get {
                return ResourceManager.GetString("BuyViewModel_Caption", resourceCulture);
            }
        }
        
        public static string BuyViewModel_Keywords {
            get {
                return ResourceManager.GetString("BuyViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string DocsLinkViewModel_Title {
            get {
                return ResourceManager.GetString("DocsLinkViewModel_Title", resourceCulture);
            }
        }
        
        public static string DocsLinkViewModel_Caption {
            get {
                return ResourceManager.GetString("DocsLinkViewModel_Caption", resourceCulture);
            }
        }
        
        public static string DocsLinkViewModel_Keywords {
            get {
                return ResourceManager.GetString("DocsLinkViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string GeneralSettingsTabViewModel_Title {
            get {
                return ResourceManager.GetString("GeneralSettingsTabViewModel_Title", resourceCulture);
            }
        }
        
        public static string GeneralSettingsTabViewModel_Caption {
            get {
                return ResourceManager.GetString("GeneralSettingsTabViewModel_Caption", resourceCulture);
            }
        }
        
        public static string GeneralSettingsTabViewModel_Keywords {
            get {
                return ResourceManager.GetString("GeneralSettingsTabViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string GeneralSettingsTabViewModel_Error_CouldntSaveChanges_Message {
            get {
                return ResourceManager.GetString("GeneralSettingsTabViewModel_Error_CouldntSaveChanges_Message", resourceCulture);
            }
        }
        
        public static string GeneralSettingsTabViewModel_Error_CouldntSaveChanges_Caption {
            get {
                return ResourceManager.GetString("GeneralSettingsTabViewModel_Error_CouldntSaveChanges_Caption", resourceCulture);
            }
        }
        
        public static string OpenConfigFileViewModel_Title {
            get {
                return ResourceManager.GetString("OpenConfigFileViewModel_Title", resourceCulture);
            }
        }
        
        public static string OpenConfigFileViewModel_Keywords {
            get {
                return ResourceManager.GetString("OpenConfigFileViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string OpenDataFolderViewModel_Title {
            get {
                return ResourceManager.GetString("OpenDataFolderViewModel_Title", resourceCulture);
            }
        }
        
        public static string OpenDataFolderViewModel_Keywords {
            get {
                return ResourceManager.GetString("OpenDataFolderViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string OpenLogsViewModel_Title {
            get {
                return ResourceManager.GetString("OpenLogsViewModel_Title", resourceCulture);
            }
        }
        
        public static string OpenLogsViewModel_Keywords {
            get {
                return ResourceManager.GetString("OpenLogsViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string OpenTorLogsViewModel_Title {
            get {
                return ResourceManager.GetString("OpenTorLogsViewModel_Title", resourceCulture);
            }
        }
        
        public static string OpenTorLogsViewModel_Keywords {
            get {
                return ResourceManager.GetString("OpenTorLogsViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string OpenWalletsFolderViewModel_Title {
            get {
                return ResourceManager.GetString("OpenWalletsFolderViewModel_Title", resourceCulture);
            }
        }
        
        public static string OpenWalletsFolderViewModel_Keywords {
            get {
                return ResourceManager.GetString("OpenWalletsFolderViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string ReceiveViewModel_Title {
            get {
                return ResourceManager.GetString("ReceiveViewModel_Title", resourceCulture);
            }
        }
        
        public static string ReceiveViewModel_Caption {
            get {
                return ResourceManager.GetString("ReceiveViewModel_Caption", resourceCulture);
            }
        }
        
        public static string ReceiveViewModel_Keywords {
            get {
                return ResourceManager.GetString("ReceiveViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string SendViewModel_Title {
            get {
                return ResourceManager.GetString("SendViewModel_Title", resourceCulture);
            }
        }
        
        public static string SendViewModel_Caption {
            get {
                return ResourceManager.GetString("SendViewModel_Caption", resourceCulture);
            }
        }
        
        public static string SendViewModel_Keywords {
            get {
                return ResourceManager.GetString("SendViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string SendViewModel_Error_Amount_LessThanSupply_Message {
            get {
                return ResourceManager.GetString("SendViewModel_Error_Amount_LessThanSupply_Message", resourceCulture);
            }
        }
        
        public static string SendViewModel_Error_Amount_InsufficientFunds_Message {
            get {
                return ResourceManager.GetString("SendViewModel_Error_Amount_InsufficientFunds_Message", resourceCulture);
            }
        }
        
        public static string SendViewModel_Error_Amount_Negative_Message {
            get {
                return ResourceManager.GetString("SendViewModel_Error_Amount_Negative_Message", resourceCulture);
            }
        }
        
        public static string SendViewModel_Error_Address_Invalid_Message {
            get {
                return ResourceManager.GetString("SendViewModel_Error_Address_Invalid_Message", resourceCulture);
            }
        }
        
        public static string SendViewModel_Error_Payjoin_HardwareWalletNotPossible_Message {
            get {
                return ResourceManager.GetString("SendViewModel_Error_Payjoin_HardwareWalletNotPossible_Message", resourceCulture);
            }
        }
        
        public static string SettingsPageViewModel_Title {
            get {
                return ResourceManager.GetString("SettingsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string SettingsPageViewModel_Caption {
            get {
                return ResourceManager.GetString("SettingsPageViewModel_Caption", resourceCulture);
            }
        }
        
        public static string SettingsPageViewModel_Keywords {
            get {
                return ResourceManager.GetString("SettingsPageViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string SettingsPageViewModel_Restart {
            get {
                return ResourceManager.GetString("SettingsPageViewModel_Restart", resourceCulture);
            }
        }
        
        public static string UserSupportViewModel_Title {
            get {
                return ResourceManager.GetString("UserSupportViewModel_Title", resourceCulture);
            }
        }
        
        public static string UserSupportViewModel_Caption {
            get {
                return ResourceManager.GetString("UserSupportViewModel_Caption", resourceCulture);
            }
        }
        
        public static string UserSupportViewModel_Keywords {
            get {
                return ResourceManager.GetString("UserSupportViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string WalletCoinJoinSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("WalletCoinJoinSettingsViewModel_Title", resourceCulture);
            }
        }
        
        public static string WalletCoinJoinSettingsViewModel_Caption {
            get {
                return ResourceManager.GetString("WalletCoinJoinSettingsViewModel_Caption", resourceCulture);
            }
        }
        
        public static string WalletCoinJoinSettingsViewModel_Keywords {
            get {
                return ResourceManager.GetString("WalletCoinJoinSettingsViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string WalletCoinsViewModel_Title {
            get {
                return ResourceManager.GetString("WalletCoinsViewModel_Title", resourceCulture);
            }
        }
        
        public static string WalletCoinsViewModel_Caption {
            get {
                return ResourceManager.GetString("WalletCoinsViewModel_Caption", resourceCulture);
            }
        }
        
        public static string WalletCoinsViewModel_Keywords {
            get {
                return ResourceManager.GetString("WalletCoinsViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string WalletInfoViewModel_Title {
            get {
                return ResourceManager.GetString("WalletInfoViewModel_Title", resourceCulture);
            }
        }
        
        public static string WalletInfoViewModel_Caption {
            get {
                return ResourceManager.GetString("WalletInfoViewModel_Caption", resourceCulture);
            }
        }
        
        public static string WalletInfoViewModel_Keywords {
            get {
                return ResourceManager.GetString("WalletInfoViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string WalletSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("WalletSettingsViewModel_Title", resourceCulture);
            }
        }
        
        public static string WalletSettingsViewModel_Caption {
            get {
                return ResourceManager.GetString("WalletSettingsViewModel_Caption", resourceCulture);
            }
        }
        
        public static string WalletSettingsViewModel_Keywords {
            get {
                return ResourceManager.GetString("WalletSettingsViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string WalletStatsViewModel_Title {
            get {
                return ResourceManager.GetString("WalletStatsViewModel_Title", resourceCulture);
            }
        }
        
        public static string WalletStatsViewModel_Caption {
            get {
                return ResourceManager.GetString("WalletStatsViewModel_Caption", resourceCulture);
            }
        }
        
        public static string WalletStatsViewModel_Keywords {
            get {
                return ResourceManager.GetString("WalletStatsViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string FindCoordinatorLinkViewModel_Title {
            get {
                return ResourceManager.GetString("FindCoordinatorLinkViewModel_Title", resourceCulture);
            }
        }
        
        public static string FindCoordinatorLinkViewModel_Caption {
            get {
                return ResourceManager.GetString("FindCoordinatorLinkViewModel_Caption", resourceCulture);
            }
        }
        
        public static string FindCoordinatorLinkViewModel_Keywords {
            get {
                return ResourceManager.GetString("FindCoordinatorLinkViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string CoordinatorTabSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("CoordinatorTabSettingsViewModel_Title", resourceCulture);
            }
        }
        
        public static string CoordinatorTabSettingsViewModel_Caption {
            get {
                return ResourceManager.GetString("CoordinatorTabSettingsViewModel_Caption", resourceCulture);
            }
        }
        
        public static string CoordinatorTabSettingsViewModel_Keywords {
            get {
                return ResourceManager.GetString("CoordinatorTabSettingsViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string AddedWalletPageViewModel_Title {
            get {
                return ResourceManager.GetString("AddedWalletPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string AddressLabelEditViewModel_Title {
            get {
                return ResourceManager.GetString("AddressLabelEditViewModel_Title", resourceCulture);
            }
        }
        
        public static string AuthorizationDialogBase_AuthorizationFailed_Message {
            get {
                return ResourceManager.GetString("AuthorizationDialogBase_AuthorizationFailed_Message", resourceCulture);
            }
        }
        
        public static string AdvancedRecoveryOptionsViewModel_Title {
            get {
                return ResourceManager.GetString("AdvancedRecoveryOptionsViewModel_Title", resourceCulture);
            }
        }
        
        public static string BroadcastTransactionViewModel_Title {
            get {
                return ResourceManager.GetString("BroadcastTransactionViewModel_Title", resourceCulture);
            }
        }
        
        public static string BroadcastTransactionViewModel_Error_Generic_Caption {
            get {
                return ResourceManager.GetString("BroadcastTransactionViewModel_Error_Generic_Caption", resourceCulture);
            }
        }
        
        public static string CancelTransactionDialogViewModel_Title {
            get {
                return ResourceManager.GetString("CancelTransactionDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string CancelTransactionDialogViewModel_Success {
            get {
                return ResourceManager.GetString("CancelTransactionDialogViewModel_Success", resourceCulture);
            }
        }
        
        public static string CancelTransactionDialogViewModel_Error_AlreadyConfirmed_Title {
            get {
                return ResourceManager.GetString("CancelTransactionDialogViewModel_Error_AlreadyConfirmed_Title", resourceCulture);
            }
        }
        
        public static string CancelTransactionDialogViewModel_Error_AlreadyConfirmed_Caption {
            get {
                return ResourceManager.GetString("CancelTransactionDialogViewModel_Error_AlreadyConfirmed_Caption", resourceCulture);
            }
        }
        
        public static string CancelTransactionDialogViewModel_Error_AlreadyConfirmed_Message {
            get {
                return ResourceManager.GetString("CancelTransactionDialogViewModel_Error_AlreadyConfirmed_Message", resourceCulture);
            }
        }
        
        public static string CoinJoinDetailsViewModel_Title {
            get {
                return ResourceManager.GetString("CoinJoinDetailsViewModel_Title", resourceCulture);
            }
        }
        
        public static string CoinJoinProfilesViewModel_Title {
            get {
                return ResourceManager.GetString("CoinJoinProfilesViewModel_Title", resourceCulture);
            }
        }
        
        public static string CoinJoinsDetailsViewModel_Title {
            get {
                return ResourceManager.GetString("CoinJoinsDetailsViewModel_Title", resourceCulture);
            }
        }
        
        public static string ConfirmDeleteOrderDialogViewModel_Title {
            get {
                return ResourceManager.GetString("ConfirmDeleteOrderDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string ConfirmHideAddressViewModel_Title {
            get {
                return ResourceManager.GetString("ConfirmHideAddressViewModel_Title", resourceCulture);
            }
        }
        
        public static string ConfirmRecoveryWordsViewModel_Title {
            get {
                return ResourceManager.GetString("ConfirmRecoveryWordsViewModel_Title", resourceCulture);
            }
        }
        
        public static string ConfirmRecoveryWordsViewModel_AddPassphrase_Title {
            get {
                return ResourceManager.GetString("ConfirmRecoveryWordsViewModel_AddPassphrase_Title", resourceCulture);
            }
        }
        
        public static string ConfirmRecoveryWordsViewModel_AddPassphrase_Caption {
            get {
                return ResourceManager.GetString("ConfirmRecoveryWordsViewModel_AddPassphrase_Caption", resourceCulture);
            }
        }
        
        public static string ConnectHardwareWalletViewModel_Title {
            get {
                return ResourceManager.GetString("ConnectHardwareWalletViewModel_Title", resourceCulture);
            }
        }
        
        public static string ConnectHardwareWalletViewModel_EvaluateDetection_ConnectPcEnterPin {
            get {
                return ResourceManager.GetString("ConnectHardwareWalletViewModel_EvaluateDetection_ConnectPcEnterPin", resourceCulture);
            }
        }
        
        public static string ConnectHardwareWalletViewModel_EvaluateDetection_MakeSureOnlyOne {
            get {
                return ResourceManager.GetString("ConnectHardwareWalletViewModel_EvaluateDetection_MakeSureOnlyOne", resourceCulture);
            }
        }
        
        public static string ConnectHardwareWalletViewModel_EvaluateDetection_AlreadyAdded {
            get {
                return ResourceManager.GetString("ConnectHardwareWalletViewModel_EvaluateDetection_AlreadyAdded", resourceCulture);
            }
        }
        
        public static string ConnectHardwareWalletViewModel_EvaluateDetection_ColdcardNotInitialized {
            get {
                return ResourceManager.GetString("ConnectHardwareWalletViewModel_EvaluateDetection_ColdcardNotInitialized", resourceCulture);
            }
        }
        
        public static string ConnectHardwareWalletViewModel_EvaluateDetection_OtherNotInitialized {
            get {
                return ResourceManager.GetString("ConnectHardwareWalletViewModel_EvaluateDetection_OtherNotInitialized", resourceCulture);
            }
        }
        
        public static string ConnectHardwareWalletViewModel_EvaluateDetection_CodeRequested {
            get {
                return ResourceManager.GetString("ConnectHardwareWalletViewModel_EvaluateDetection_CodeRequested", resourceCulture);
            }
        }
        
        public static string ConnectHardwareWalletViewModel_EvaluateDetection_PassphraseRequested {
            get {
                return ResourceManager.GetString("ConnectHardwareWalletViewModel_EvaluateDetection_PassphraseRequested", resourceCulture);
            }
        }
        
        public static string ConnectHardwareWalletViewModel_EvaluateDetection_PinRequested {
            get {
                return ResourceManager.GetString("ConnectHardwareWalletViewModel_EvaluateDetection_PinRequested", resourceCulture);
            }
        }
        
        public static string CustomFeeRateDialogViewModel_Title {
            get {
                return ResourceManager.GetString("CustomFeeRateDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string CustomFeeRateDialogViewModel_Error_FeeEntered_Invalid {
            get {
                return ResourceManager.GetString("CustomFeeRateDialogViewModel_Error_FeeEntered_Invalid", resourceCulture);
            }
        }
        
        public static string CustomFeeRateDialogViewModel_Error_FeeEntered_TooLow {
            get {
                return ResourceManager.GetString("CustomFeeRateDialogViewModel_Error_FeeEntered_TooLow", resourceCulture);
            }
        }
        
        public static string CustomFeeRateDialogViewModel_Error_FeeEntered_TooHigh {
            get {
                return ResourceManager.GetString("CustomFeeRateDialogViewModel_Error_FeeEntered_TooHigh", resourceCulture);
            }
        }
        
        public static string DetectedHardwareWalletViewModel_Title {
            get {
                return ResourceManager.GetString("DetectedHardwareWalletViewModel_Title", resourceCulture);
            }
        }
        
        public static string DetectedHardwareWalletViewModel_Error_AddingWallet_Caption {
            get {
                return ResourceManager.GetString("DetectedHardwareWalletViewModel_Error_AddingWallet_Caption", resourceCulture);
            }
        }
        
        public static string EconomicCoinJoinProfileViewModel_Title {
            get {
                return ResourceManager.GetString("EconomicCoinJoinProfileViewModel_Title", resourceCulture);
            }
        }
        
        public static string EconomicCoinJoinProfileViewModel_Description {
            get {
                return ResourceManager.GetString("EconomicCoinJoinProfileViewModel_Description", resourceCulture);
            }
        }
        
        public static string ExcludedCoinsViewModel_Title {
            get {
                return ResourceManager.GetString("ExcludedCoinsViewModel_Title", resourceCulture);
            }
        }
        
        public static string ExcludedCoinsViewModel_Caption {
            get {
                return ResourceManager.GetString("ExcludedCoinsViewModel_Caption", resourceCulture);
            }
        }
        
        public static string ExcludedCoinsViewModel_Keywords {
            get {
                return ResourceManager.GetString("ExcludedCoinsViewModel_Keywords", resourceCulture);
            }
        }
        
        public static string HardwareWalletAuthDialogViewModel_Title {
            get {
                return ResourceManager.GetString("HardwareWalletAuthDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string HardwareWalletAuthDialogViewModel_Error_AuthorizationFailed {
            get {
                return ResourceManager.GetString("HardwareWalletAuthDialogViewModel_Error_AuthorizationFailed", resourceCulture);
            }
        }
        
        public static string LabelSelectionViewModel_NoInformation_Tip {
            get {
                return ResourceManager.GetString("LabelSelectionViewModel_NoInformation_Tip", resourceCulture);
            }
        }
        
        public static string LoadingViewModel_PercentCompleted {
            get {
                return ResourceManager.GetString("LoadingViewModel_PercentCompleted", resourceCulture);
            }
        }
        
        public static string LoadingViewModel_TimeRemaining {
            get {
                return ResourceManager.GetString("LoadingViewModel_TimeRemaining", resourceCulture);
            }
        }
        
        public static string LoadTransactionViewModel_Title {
            get {
                return ResourceManager.GetString("LoadTransactionViewModel_Title", resourceCulture);
            }
        }
        
        public static string LoadTransactionViewModel_ImportTransaction_Title {
            get {
                return ResourceManager.GetString("LoadTransactionViewModel_ImportTransaction_Title", resourceCulture);
            }
        }
        
        public static string LoadTransactionViewModel_Error_LoadTransaction_Caption {
            get {
                return ResourceManager.GetString("LoadTransactionViewModel_Error_LoadTransaction_Caption", resourceCulture);
            }
        }
        
        public static string LoadTransactionViewModel_Error_PasteTransaction_Caption {
            get {
                return ResourceManager.GetString("LoadTransactionViewModel_Error_PasteTransaction_Caption", resourceCulture);
            }
        }
        
        public static string LoginViewModel_Error_PassphraseIncorrect_Message {
            get {
                return ResourceManager.GetString("LoginViewModel_Error_PassphraseIncorrect_Message", resourceCulture);
            }
        }
        
        public static string LoginViewModel_Error_CompatibilityPasswordUsed_Caption {
            get {
                return ResourceManager.GetString("LoginViewModel_Error_CompatibilityPasswordUsed_Caption", resourceCulture);
            }
        }
        
        public static string ManualCoinJoinProfileDialogViewModel_Title {
            get {
                return ResourceManager.GetString("ManualCoinJoinProfileDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string ManualCoinJoinProfileViewModel_Title {
            get {
                return ResourceManager.GetString("ManualCoinJoinProfileViewModel_Title", resourceCulture);
            }
        }
        
        public static string ManualControlDialogViewModel_Title {
            get {
                return ResourceManager.GetString("ManualControlDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string NewCoordinatorConfirmationDialogViewModel_Title {
            get {
                return ResourceManager.GetString("NewCoordinatorConfirmationDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string NewWalletAdvancedOptionsDialogViewModel_Title {
            get {
                return ResourceManager.GetString("NewWalletAdvancedOptionsDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string PasswordAuthDialogViewModel_Title {
            get {
                return ResourceManager.GetString("PasswordAuthDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string PasswordAuthDialogViewModel_Error_AuthorizationFailed_Message {
            get {
                return ResourceManager.GetString("PasswordAuthDialogViewModel_Error_AuthorizationFailed_Message", resourceCulture);
            }
        }
        
        public static string PrivacyControlViewModel_Title {
            get {
                return ResourceManager.GetString("PrivacyControlViewModel_Title", resourceCulture);
            }
        }
        
        public static string PrivacyModeViewModel_Title {
            get {
                return ResourceManager.GetString("PrivacyModeViewModel_Title", resourceCulture);
            }
        }
        
        public static string PrivacyRingViewModel_Title {
            get {
                return ResourceManager.GetString("PrivacyRingViewModel_Title", resourceCulture);
            }
        }
        
        public static string PrivateCoinJoinProfileViewModel_Title {
            get {
                return ResourceManager.GetString("PrivateCoinJoinProfileViewModel_Title", resourceCulture);
            }
        }
        
        public static string PrivateCoinJoinProfileViewModel_Description {
            get {
                return ResourceManager.GetString("PrivateCoinJoinProfileViewModel_Description", resourceCulture);
            }
        }
        
        public static string ReceiveAddressesViewModel_Title {
            get {
                return ResourceManager.GetString("ReceiveAddressesViewModel_Title", resourceCulture);
            }
        }
        
        public static string ReceiveAddressViewModel_Title {
            get {
                return ResourceManager.GetString("ReceiveAddressViewModel_Title", resourceCulture);
            }
        }
        
        public static string ReceiveAddressViewModel_Error_UnableToSendAddressToDevice_Caption {
            get {
                return ResourceManager.GetString("ReceiveAddressViewModel_Error_UnableToSendAddressToDevice_Caption", resourceCulture);
            }
        }
        
        public static string RecoverWalletViewModel_Title {
            get {
                return ResourceManager.GetString("RecoverWalletViewModel_Title", resourceCulture);
            }
        }
        
        public static string RecoverWalletViewModel_CreatePassword_Title {
            get {
                return ResourceManager.GetString("RecoverWalletViewModel_CreatePassword_Title", resourceCulture);
            }
        }
        
        public static string RecoverWalletViewModel_CreatePassword_Caption {
            get {
                return ResourceManager.GetString("RecoverWalletViewModel_CreatePassword_Caption", resourceCulture);
            }
        }
        
        public static string RecoverWalletViewModel_Error_NotAbleRecover_Caption {
            get {
                return ResourceManager.GetString("RecoverWalletViewModel_Error_NotAbleRecover_Caption", resourceCulture);
            }
        }
        
        public static string RecoverWalletViewModel_Error_InvalidSet_Message {
            get {
                return ResourceManager.GetString("RecoverWalletViewModel_Error_InvalidSet_Message", resourceCulture);
            }
        }
        
        public static string RecoveryWordsViewModel_Title {
            get {
                return ResourceManager.GetString("RecoveryWordsViewModel_Title", resourceCulture);
            }
        }
        
        public static string OpenFileViewModel_Error_Generic_Title {
            get {
                return ResourceManager.GetString("OpenFileViewModel_Error_Generic_Title", resourceCulture);
            }
        }
        
        public static string OpenFileViewModel_Error_Generic_Caption {
            get {
                return ResourceManager.GetString("OpenFileViewModel_Error_Generic_Caption", resourceCulture);
            }
        }
        
        public static string SelectCoinsDialogViewModel_Title {
            get {
                return ResourceManager.GetString("SelectCoinsDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string SendFeeViewModel_Title {
            get {
                return ResourceManager.GetString("SendFeeViewModel_Title", resourceCulture);
            }
        }
        
        public static string SendFeeViewModel_Error_TransactionFee_Title {
            get {
                return ResourceManager.GetString("SendFeeViewModel_Error_TransactionFee_Title", resourceCulture);
            }
        }
        
        public static string SendFeeViewModel_Error_TransactionFee_Message {
            get {
                return ResourceManager.GetString("SendFeeViewModel_Error_TransactionFee_Message", resourceCulture);
            }
        }
        
        public static string SendSuccessViewModel_Title {
            get {
                return ResourceManager.GetString("SendSuccessViewModel_Title", resourceCulture);
            }
        }
        
        public static string SendSuccessViewModel_Caption {
            get {
                return ResourceManager.GetString("SendSuccessViewModel_Caption", resourceCulture);
            }
        }
        
        public static string ShowQrCameraDialogViewModel_Title {
            get {
                return ResourceManager.GetString("ShowQrCameraDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string ShowQrCameraDialogViewModel_Error_Generic_Caption {
            get {
                return ResourceManager.GetString("ShowQrCameraDialogViewModel_Error_Generic_Caption", resourceCulture);
            }
        }
        
        public static string ShuttingDownViewModel_Title {
            get {
                return ResourceManager.GetString("ShuttingDownViewModel_Title", resourceCulture);
            }
        }
        
        public static string SpeedUpTransactionDialogViewModel_Title {
            get {
                return ResourceManager.GetString("SpeedUpTransactionDialogViewModel_Title", resourceCulture);
            }
        }
        
        public static string SpeedUpTransactionDialogViewModel_Success_Caption {
            get {
                return ResourceManager.GetString("SpeedUpTransactionDialogViewModel_Success_Caption", resourceCulture);
            }
        }
        
        public static string SpeedUpTransactionDialogViewModel_Error_Generic_Title {
            get {
                return ResourceManager.GetString("SpeedUpTransactionDialogViewModel_Error_Generic_Title", resourceCulture);
            }
        }
        
        public static string SpeedUpTransactionDialogViewModel_Error_Generic_Caption {
            get {
                return ResourceManager.GetString("SpeedUpTransactionDialogViewModel_Error_Generic_Caption", resourceCulture);
            }
        }
        
        public static string SpeedUpTransactionDialogViewModel_Error_AlreadyConfirmed_Message {
            get {
                return ResourceManager.GetString("SpeedUpTransactionDialogViewModel_Error_AlreadyConfirmed_Message", resourceCulture);
            }
        }
        
        public static string SpeedyCoinJoinProfile_Title {
            get {
                return ResourceManager.GetString("SpeedyCoinJoinProfile_Title", resourceCulture);
            }
        }
        
        public static string SpeedyCoinJoinProfile_Description {
            get {
                return ResourceManager.GetString("SpeedyCoinJoinProfile_Description", resourceCulture);
            }
        }
        
        public static string SuccessViewModel_Title {
            get {
                return ResourceManager.GetString("SuccessViewModel_Title", resourceCulture);
            }
        }
        
        public static string StatusIconViewModel_NewVersion_ReadyToInstall {
            get {
                return ResourceManager.GetString("StatusIconViewModel_NewVersion_ReadyToInstall", resourceCulture);
            }
        }
        
        public static string StatusIconViewModel_NewVersion_Available {
            get {
                return ResourceManager.GetString("StatusIconViewModel_NewVersion_Available", resourceCulture);
            }
        }
        
        public static string TransactionDetailsViewModel_Title {
            get {
                return ResourceManager.GetString("TransactionDetailsViewModel_Title", resourceCulture);
            }
        }
        
        public static string TransactionPreviewViewModel_Title {
            get {
                return ResourceManager.GetString("TransactionPreviewViewModel_Title", resourceCulture);
            }
        }
        
        public static string TransactionPreviewViewModel_PSBT_Next {
            get {
                return ResourceManager.GetString("TransactionPreviewViewModel_PSBT_Next", resourceCulture);
            }
        }
        
        public static string TransactionPreviewViewModel_PSBT_Error_UnableExport_Title {
            get {
                return ResourceManager.GetString("TransactionPreviewViewModel_PSBT_Error_UnableExport_Title", resourceCulture);
            }
        }
        
        public static string TransactionPreviewViewModel_PSBT_Error_UnableExport_Caption {
            get {
                return ResourceManager.GetString("TransactionPreviewViewModel_PSBT_Error_UnableExport_Caption", resourceCulture);
            }
        }
        
        public static string TransactionPreviewViewModel_Standard_Next {
            get {
                return ResourceManager.GetString("TransactionPreviewViewModel_Standard_Next", resourceCulture);
            }
        }
        
        public static string TransactionPreviewViewModel_Standard_Error_Generic_Title {
            get {
                return ResourceManager.GetString("TransactionPreviewViewModel_Standard_Error_Generic_Title", resourceCulture);
            }
        }
        
        public static string TransactionPreviewViewModel_Standard_Error_Generic_Caption {
            get {
                return ResourceManager.GetString("TransactionPreviewViewModel_Standard_Error_Generic_Caption", resourceCulture);
            }
        }
        
        public static string TransactionPreviewViewModel_Standard_Error_FeeExceedsPayment_Message {
            get {
                return ResourceManager.GetString("TransactionPreviewViewModel_Standard_Error_FeeExceedsPayment_Message", resourceCulture);
            }
        }
        
        public static string TransactionPreviewViewModel_Standard_Error_InsufficientFundsForFee_Message {
            get {
                return ResourceManager.GetString("TransactionPreviewViewModel_Standard_Error_InsufficientFundsForFee_Message", resourceCulture);
            }
        }
        
        public static string WalletNamePageViewModel_Title {
            get {
                return ResourceManager.GetString("WalletNamePageViewModel_Title", resourceCulture);
            }
        }
        
        public static string WalletNamePageViewModel_Error_UnableImport_Title {
            get {
                return ResourceManager.GetString("WalletNamePageViewModel_Error_UnableImport_Title", resourceCulture);
            }
        }
        
        public static string WalletNamePageViewModel_Error_UnableImport_Caption {
            get {
                return ResourceManager.GetString("WalletNamePageViewModel_Error_UnableImport_Caption", resourceCulture);
            }
        }
        
        public static string WalletRenameViewModel_Title {
            get {
                return ResourceManager.GetString("WalletRenameViewModel_Title", resourceCulture);
            }
        }
        
        public static string WalletVerifyRecoveryWordsViewModel_Title {
            get {
                return ResourceManager.GetString("WalletVerifyRecoveryWordsViewModel_Title", resourceCulture);
            }
        }
        
        public static string MusicBox_CountDownMessage {
            get {
                return ResourceManager.GetString("MusicBox_CountDownMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_WaitingMessage {
            get {
                return ResourceManager.GetString("MusicBox_WaitingMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_UneconomicalRoundMessage {
            get {
                return ResourceManager.GetString("MusicBox_UneconomicalRoundMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_RandomlySkippedRoundMessage {
            get {
                return ResourceManager.GetString("MusicBox_RandomlySkippedRoundMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_CoinjoinMiningFeeRateTooHighMessage {
            get {
                return ResourceManager.GetString("MusicBox_CoinjoinMiningFeeRateTooHighMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_MinInputCountTooLowMessage {
            get {
                return ResourceManager.GetString("MusicBox_MinInputCountTooLowMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_PauseMessage {
            get {
                return ResourceManager.GetString("MusicBox_PauseMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_StoppedMessage {
            get {
                return ResourceManager.GetString("MusicBox_StoppedMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_PressPlayToStartMessage {
            get {
                return ResourceManager.GetString("MusicBox_PressPlayToStartMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_RoundSucceedMessage {
            get {
                return ResourceManager.GetString("MusicBox_RoundSucceedMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_RoundFinishedMessage {
            get {
                return ResourceManager.GetString("MusicBox_RoundFinishedMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_AbortedNotEnoughAlicesMessage {
            get {
                return ResourceManager.GetString("MusicBox_AbortedNotEnoughAlicesMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_CoinJoinInProgress {
            get {
                return ResourceManager.GetString("MusicBox_CoinJoinInProgress", resourceCulture);
            }
        }
        
        public static string MusicBox_InputRegistrationMessage {
            get {
                return ResourceManager.GetString("MusicBox_InputRegistrationMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_WaitingForBlameRoundMessage {
            get {
                return ResourceManager.GetString("MusicBox_WaitingForBlameRoundMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_WaitingRoundMessage {
            get {
                return ResourceManager.GetString("MusicBox_WaitingRoundMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_PlebStopMessage {
            get {
                return ResourceManager.GetString("MusicBox_PlebStopMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_PlebStopMessageBelow {
            get {
                return ResourceManager.GetString("MusicBox_PlebStopMessageBelow", resourceCulture);
            }
        }
        
        public static string MusicBox_NoCoinsEligibleToMixMessage {
            get {
                return ResourceManager.GetString("MusicBox_NoCoinsEligibleToMixMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_UserInSendWorkflowMessage {
            get {
                return ResourceManager.GetString("MusicBox_UserInSendWorkflowMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_AllPrivateMessage {
            get {
                return ResourceManager.GetString("MusicBox_AllPrivateMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_BackendNotConnected {
            get {
                return ResourceManager.GetString("MusicBox_BackendNotConnected", resourceCulture);
            }
        }
        
        public static string MusicBox_GeneralErrorMessage {
            get {
                return ResourceManager.GetString("MusicBox_GeneralErrorMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_WaitingForConfirmedFunds {
            get {
                return ResourceManager.GetString("MusicBox_WaitingForConfirmedFunds", resourceCulture);
            }
        }
        
        public static string MusicBox_CoinsRejectedMessage {
            get {
                return ResourceManager.GetString("MusicBox_CoinsRejectedMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_OnlyImmatureCoinsAvailableMessage {
            get {
                return ResourceManager.GetString("MusicBox_OnlyImmatureCoinsAvailableMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_OnlyExcludedCoinsAvailableMessage {
            get {
                return ResourceManager.GetString("MusicBox_OnlyExcludedCoinsAvailableMessage", resourceCulture);
            }
        }
        
        public static string MusicBox_WaitingForResponse {
            get {
                return ResourceManager.GetString("MusicBox_WaitingForResponse", resourceCulture);
            }
        }
        
        public static string CLI_NetworkSettingsHint {
            get {
                return ResourceManager.GetString("CLI_NetworkSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_MainNetBackendUriSettingsHint {
            get {
                return ResourceManager.GetString("CLI_MainNetBackendUriSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_TestNetBackendUriSettingsHint {
            get {
                return ResourceManager.GetString("CLI_TestNetBackendUriSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_RegTestBackendUriSettingsHint {
            get {
                return ResourceManager.GetString("CLI_RegTestBackendUriSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_MainNetCoordinatorUriSettingsHint {
            get {
                return ResourceManager.GetString("CLI_MainNetCoordinatorUriSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_TestNetCoordinatorUriSettingsHint {
            get {
                return ResourceManager.GetString("CLI_TestNetCoordinatorUriSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_RegTestCoordinatorUriSettingsHint {
            get {
                return ResourceManager.GetString("CLI_RegTestCoordinatorUriSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_UseTorSettingsHint {
            get {
                return ResourceManager.GetString("CLI_UseTorSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_TorFolderSettingsHint {
            get {
                return ResourceManager.GetString("CLI_TorFolderSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_TorSocksPortSettingsHint {
            get {
                return ResourceManager.GetString("CLI_TorSocksPortSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_TorControlPortSettingsHint {
            get {
                return ResourceManager.GetString("CLI_TorControlPortSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_TorBridgesSettingsHint {
            get {
                return ResourceManager.GetString("CLI_TorBridgesSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_TerminateTorOnExitSettingsHint {
            get {
                return ResourceManager.GetString("CLI_TerminateTorOnExitSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_DownloadNewVersionSettingsHint {
            get {
                return ResourceManager.GetString("CLI_DownloadNewVersionSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_StartLocalBitcoinCoreOnStartupSettingsHint {
            get {
                return ResourceManager.GetString("CLI_StartLocalBitcoinCoreOnStartupSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_StopLocalBitcoinCoreOnShutdownSettingsHint {
            get {
                return ResourceManager.GetString("CLI_StopLocalBitcoinCoreOnShutdownSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_LocalBitcoinCoreDataDirSettingsHint {
            get {
                return ResourceManager.GetString("CLI_LocalBitcoinCoreDataDirSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_JsonRpcServerEnabledSettingsHint {
            get {
                return ResourceManager.GetString("CLI_JsonRpcServerEnabledSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_JsonRpcUserSettingsHint {
            get {
                return ResourceManager.GetString("CLI_JsonRpcUserSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_JsonRpcPasswordSettingsHint {
            get {
                return ResourceManager.GetString("CLI_JsonRpcPasswordSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_JsonRpcServerPrefixesSettingsHint {
            get {
                return ResourceManager.GetString("CLI_JsonRpcServerPrefixesSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_RpcOnionEnabledSettingsHint {
            get {
                return ResourceManager.GetString("CLI_RpcOnionEnabledSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_DustThresholdSettingsHint {
            get {
                return ResourceManager.GetString("CLI_DustThresholdSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_BlockOnlyModeSettingsHint {
            get {
                return ResourceManager.GetString("CLI_BlockOnlyModeSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_LogLevelSettingsHint {
            get {
                return ResourceManager.GetString("CLI_LogLevelSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_LogModesSettingsHint {
            get {
                return ResourceManager.GetString("CLI_LogModesSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_EnableGpuSettingsHint {
            get {
                return ResourceManager.GetString("CLI_EnableGpuSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_MaxCoinjoinMiningFeeRateSettingsHint {
            get {
                return ResourceManager.GetString("CLI_MaxCoinjoinMiningFeeRateSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_AbsoluteMinInputCountSettingsHint {
            get {
                return ResourceManager.GetString("CLI_AbsoluteMinInputCountSettingsHint", resourceCulture);
            }
        }
        
        public static string CLI_LanguageSettingsHint {
            get {
                return ResourceManager.GetString("CLI_LanguageSettingsHint", resourceCulture);
            }
        }
        
        public static string Exception_Generic_Friendly {
            get {
                return ResourceManager.GetString("Exception_Generic_Friendly", resourceCulture);
            }
        }
        
        public static string Exception_HttpRequest_Friendly {
            get {
                return ResourceManager.GetString("Exception_HttpRequest_Friendly", resourceCulture);
            }
        }
        
        public static string Exception_UnauthorizedAccess_Friendly {
            get {
                return ResourceManager.GetString("Exception_UnauthorizedAccess_Friendly", resourceCulture);
            }
        }
        
        public static string HWI_Error_DeviceConn {
            get {
                return ResourceManager.GetString("HWI_Error_DeviceConn", resourceCulture);
            }
        }
        
        public static string HWI_Error_ActionCanceled {
            get {
                return ResourceManager.GetString("HWI_Error_ActionCanceled", resourceCulture);
            }
        }
        
        public static string HWI_Error_Unknown {
            get {
                return ResourceManager.GetString("HWI_Error_Unknown", resourceCulture);
            }
        }
        
        public static string Password_Message_CompatibilityPasswordWarn {
            get {
                return ResourceManager.GetString("Password_Message_CompatibilityPasswordWarn", resourceCulture);
            }
        }
        
        public static string Password_Message_TrimWarn {
            get {
                return ResourceManager.GetString("Password_Message_TrimWarn", resourceCulture);
            }
        }
        
        public static string Password_Message_Matching {
            get {
                return ResourceManager.GetString("Password_Message_Matching", resourceCulture);
            }
        }
        
        public static string Password_Message_Whitespace {
            get {
                return ResourceManager.GetString("Password_Message_Whitespace", resourceCulture);
            }
        }
        
        public static string Password_Message_TooLong {
            get {
                return ResourceManager.GetString("Password_Message_TooLong", resourceCulture);
            }
        }
        
        public static string Status_Tor_Running {
            get {
                return ResourceManager.GetString("Status_Tor_Running", resourceCulture);
            }
        }
        
        public static string Status_Tor_NotRunning {
            get {
                return ResourceManager.GetString("Status_Tor_NotRunning", resourceCulture);
            }
        }
        
        public static string Status_Tor_TurnedOff {
            get {
                return ResourceManager.GetString("Status_Tor_TurnedOff", resourceCulture);
            }
        }
        
        public static string Status_Backend_Connected {
            get {
                return ResourceManager.GetString("Status_Backend_Connected", resourceCulture);
            }
        }
        
        public static string Status_Backend_NotConnected {
            get {
                return ResourceManager.GetString("Status_Backend_NotConnected", resourceCulture);
            }
        }
        
        public static string Status_Peers_ConnectedCount {
            get {
                return ResourceManager.GetString("Status_Peers_ConnectedCount", resourceCulture);
            }
        }
        
        public static string SearchCategory_NoCategory {
            get {
                return ResourceManager.GetString("SearchCategory_NoCategory", resourceCulture);
            }
        }
        
        public static string SearchCategory_General {
            get {
                return ResourceManager.GetString("SearchCategory_General", resourceCulture);
            }
        }
        
        public static string SearchCategory_Wallet {
            get {
                return ResourceManager.GetString("SearchCategory_Wallet", resourceCulture);
            }
        }
        
        public static string SearchCategory_HelpAndSupport {
            get {
                return ResourceManager.GetString("SearchCategory_HelpAndSupport", resourceCulture);
            }
        }
        
        public static string SearchCategory_Open {
            get {
                return ResourceManager.GetString("SearchCategory_Open", resourceCulture);
            }
        }
        
        public static string SearchCategory_Settings {
            get {
                return ResourceManager.GetString("SearchCategory_Settings", resourceCulture);
            }
        }
        
        public static string SearchCategory_Transactions {
            get {
                return ResourceManager.GetString("SearchCategory_Transactions", resourceCulture);
            }
        }
    }
}
