(load "Scheme/Stdlib.scm")

;; Helpers
(define (bitcoin->satoshi n) (* n 100000000))
(define (satoshi->bitcoin n) (/ n 100000000.0))

(define (native->string obj) (__get 'tostring obj))

(define (get-wallet-by-name name)
  (define (by-name wallet)
    (string=? name (wallet-name wallet)))
  (find by-name (wallets)))

(define (get-opened-wallets)
  (define (opened? wallet)
    (string=? "Started" (wallet-state wallet)))
  (filter opened? (wallets)))

(define (wallet-name wallet) (__get 'walletname wallet))
(define (wallet-path wallet) (__get 'filepath wallet))
(define (wallet-coins wallet) (__get 'coins wallet))
(define (wallet-keymanager wallet) (__get 'keymanager wallet))
(define (wallet-unspent-coins wallet) (filter coin-unspent? (wallet-coins wallet) ))
(define (wallet-state wallet) (native->string (__get 'state wallet)))

(define (wallet-watch-only? wallet)      (__get 'IsWatchOnly (wallet-keymanager wallet)))
(define (wallet-hardware-wallet? wallet) (__get 'IsHardwareWallet (wallet-keymanager wallet)))
(define (wallet-auto-coinjoin? wallet)   (__get 'AutoCoinjoin (wallet-keymanager wallet)))
(define (wallet-non-private-coin-isolation? wallet) (__get 'NonPrivateCoinIsolation (wallet-keymanager wallet)))
(define (wallet-transactions wallet)     (__get 'gettransactions wallet))

(define (transaction-wallet-inputs tx)   (__get 'walletinputs tx))
(define (transaction-wallet-outputs tx)  (__get 'walletoutputs tx))
(define (transaction-foreign-inputs tx)  (__get 'foreigninputs tx))
(define (transaction-foreign-outputs tx) (__get 'foreignoutputs tx))
(define (transaction-raw tx)             (__get 'transaction tx))
(define (transaction-height tx)          (__get 'height tx))
(define (transaction-block-hash tx)      (__get 'blockhash tx))
(define (transaction-block-index tx)     (__get 'blockindex tx))
(define (transaction-labels tx)          (__get 'labels tx))
(define (transaction-first-seen tx)      (__get 'firstseen tx))
(define (transaction-replacement? tx)    (__get 'isreplacement tx))
(define (transaction-speedup? tx)        (__get 'isspeedup tx))
(define (transaction-cancellation? tx)   (__get 'iscancellation tx))
(define (transaction-cpfp? tx)           (__get 'iscpfp tx))
(define (transaction-confirmed? tx)      (__get 'confirmed tx))

(define (coin-amount coin)               (satoshi->bitcoin (__get 'satoshi (__get 'amount coin))))
(define (coin-outpoint coin)             (__get 'outpoint coin))
(define (coin-anonymityset coin)         (__get 'anonymityset coin))
(define (coin-height coin)               (__get 'height coin))
(define (coin-spent? coin)               (__get 'isspent coin))
(define (coin-unspent? coin)             (not (coin-spent? coin)))
(define (coin-confirmed? coin)           (__get 'confirmed coin))
(define (coin-banned? coin)              (__get 'isbanned coin))
(define (coin-banned-until coin)         (__get 'banneduntilutc coin))
(define (coin-script-pukey coin)         (__get 'scriptpubkey coin))
(define (coin-script-pubkey-type coin)   (__get 'scripttype coin))
(define (coin-excluded-from-coinjoin? coin) (__get 'isexcludedfromcoinjoin coin))
(define (coin-pubkey coin)               (__get 'hdpubkey coin))
(define (coin-cluster coin)              (__get 'cluster (__get 'hdpubkey coin)))
(define (coin-labels coin)               (__get 'labels (coin-cluster coin)))
