name: "Build"
on:
  push:
    branches: [ "*" ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: wasabibinarycache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build --print-build-logs .#all
      - run: echo OK
