name: Build and Upload packages for release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  debian-package-and-zips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo bash -x ./Contrib/release.sh debian
      - uses: actions/upload-artifact@v4
        with:
          name: packages-for-debian
          path: ./packages/*.deb
          compression-level: 0
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: packages-zip-tar
          path: |
            ./packages/*
            !./packages/*.deb
          compression-level: 0
          if-no-files-found: error

  appimage-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo bash -x ./Contrib/release.sh appimage
      - uses: actions/upload-artifact@v4
        with:
          name: packages-appimage
          path: ./packages/*.AppImage
          compression-level: 0
          if-no-files-found: error

  installer-for-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: bash -x ./Contrib/release.sh wininstaller
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

      - uses: actions/upload-artifact@v4
        with:
          name: packages-for-windows
          path: ./packages/*
          compression-level: 0
          if-no-files-found: error

  macos-packages-and-zips:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./Contrib/release.sh dmg
        env:
          MAC_CER: ${{ secrets.MAC_CER }}
          MAC_P12: ${{ secrets.MAC_P12 }}
          MAC_TEAMID: ${{ secrets.MAC_TEAMID }}
          MAC_APPLEID: ${{ secrets.MAC_APPLEID }}
          MAC_APPLEPSSWD: ${{ secrets.MAC_APPLEPSSWD }}
          MAC_P12_PASSWORD: ${{ secrets.MAC_P12_PASSWORD }}

      - uses: actions/upload-artifact@v4
        with:
          name: packages-zip-dmg
          path: ./packages/*
          compression-level: 0
          if-no-files-found: error

  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [debian-package-and-zips, appimage-package, installer-for-windows, macos-packages-and-zips]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: ./packages
          merge-multiple: true
      - uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.SIGNING_PGP_KEY }}
          passphrase: ${{ secrets.SIGNING_PGP_PASSPHRASE }}
      - run: bash -x ./Contrib/release.sh sign-and-release
        env:
          SIGNING_WASABI_KEY: ${{ secrets.SIGNING_WASABI_KEY }}
          GH_TOKEN: ${{ github.token }}
